<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository {

    public function getPorcentajeActual() {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('SUM(area.ponderacion AS porcentaje')
                ->from('AppBundle:Area', 'area');
        $query = $qb->getQuery();
        $porcentaje = $query->getOneOrNullResult()['porcentaje'];
        return floatval($porcentaje);
    }

}
