<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompromisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompromisoRepository extends EntityRepository
{
    public function findBySostenedor($sostenedor)
    {
        return $this->findBy(array('sostenedor' => $sostenedor->getId()));
    }
}
