<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompromisoRealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompromisoRealRepository extends EntityRepository
{
    public function findBySostenedor($params)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('cr')
            ->from('AppBundle:CompromisoReal', 'cr')
            ->leftjoin('cr.compromiso', 'AppBundle:Compromiso')
//            ->where($qb->expr()->eq('AppBundle:Compromiso.sostenedor', ':id'))
            ->where($qb->expr()->andX(
                $qb->expr()->eq('AppBundle:Compromiso.sostenedor', ':id'),
                $qb->expr()->eq('cr.ano', ':ano')
            ))
            ->setParameters(array('ano'=>$params['ano'], 'id'=>$params['sostenedor']->getId()));
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
