<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompromisoRealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompromisoRealRepository extends EntityRepository
{
    public function findBySostenedor($sostenedor)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('cr')
            ->from('AppBundle:CompromisoReal', 'cr')
            ->leftjoin('cr.compromiso', 'AppBundle:Compromiso')
            ->where($qb->expr()->eq('AppBundle:Compromiso.sostenedor', ':id'))
            ->setParameter('id', $sostenedor->getId());
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
