# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.administrador_voter:
        class: AppBundle\Security\AdministradorVoter
        tags:
            - { name: security.voter }
        arguments: ['@security.access.decision_manager']
        public: false
    app.sostenedor_voter:
        class: AppBundle\Security\SostenedorVoter
        tags:
            - { name: security.voter }
        arguments: ['@security.access.decision_manager']
        public: false
    app.director_voter:
        class: AppBundle\Security\DirectorVoter
        tags:
            - { name: security.voter }
        arguments: ['@security.access.decision_manager']
        public: false
    app.miembro_voter:
        class: AppBundle\Security\MiembroVoter
        tags:
            - { name: security.voter }
        arguments: ['@security.access.decision_manager']
        public: false
    app.compromiso_voter:
        class: AppBundle\Security\CompromisoVoter
        tags:
            - { name: security.voter }
        arguments: ['@security.access.decision_manager']
        public: false
    app.compromisoReal_voter:
        class: AppBundle\Security\CompromisoRealVoter
        tags:
            - { name: security.voter }
        arguments: ['@security.access.decision_manager']
        public: false
    app.hito_voter:
        class: AppBundle\Security\HitoVoter
        tags:
            - { name: security.voter }
        arguments: ['@security.access.decision_manager']
        public: false
        
    authentication.handler.login_success_handler:
        class:  AppBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']
    templates.role_var_listener:
        class: AppBundle\Listener\RoleVarListener
        arguments:
            - '@twig'
            - '@security.authorization_checker'
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
    app.file_type_extension:
        class: AppBundle\Form\Extension\FileTypeExtension
        tags:
            -
                name: form.type_extension
                extended_type: Symfony\Component\Form\Extension\Core\Type\FileType      
    validator.unique.porcentaje_constraint_validator:
        class: AppBundle\Validator\Constraints\PorcentajeConstraintValidator
        tags:
            - { name: validator.constraint_validator, alias: porcentaje_constraint }
            
    app.form.type.area:
        class: AppBundle\Form\Type\AreaType
        arguments: [ '@doctrine.orm.entity_manager', '@security.token_storage' ]
        tags: 
            - { name: form.type }
    # custom fosuser user manager    
    my_pugx_user.manager.orm_user_manager:
        class:     AppBundle\Doctrine\MyUserManager
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.object_manager", %fos_user.model.user.class%, "@pugx_user.manager.user_discriminator"]
        
    my_pugx_user_manager:
        alias: my_pugx_user.manager.orm_user_manager
